// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: telemetry.proto
// Protobuf Java Version: 4.27.0

package com.example.proto;

public final class TelemetryProto {
  private TelemetryProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      TelemetryProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.telemetry.Reading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double temp = 1;</code>
     * @return The temp.
     */
    double getTemp();

    /**
     * <code>double hum = 2;</code>
     * @return The hum.
     */
    double getHum();

    /**
     * <code>bool online = 3;</code>
     * @return The online.
     */
    boolean getOnline();
  }
  /**
   * Protobuf type {@code example.telemetry.Reading}
   */
  public static final class Reading extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:example.telemetry.Reading)
      ReadingOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        Reading.class.getName());
    }
    // Use Reading.newBuilder() to construct.
    private Reading(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Reading() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.TelemetryProto.internal_static_example_telemetry_Reading_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.TelemetryProto.internal_static_example_telemetry_Reading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.TelemetryProto.Reading.class, com.example.proto.TelemetryProto.Reading.Builder.class);
    }

    public static final int TEMP_FIELD_NUMBER = 1;
    private double temp_ = 0D;
    /**
     * <code>double temp = 1;</code>
     * @return The temp.
     */
    @java.lang.Override
    public double getTemp() {
      return temp_;
    }

    public static final int HUM_FIELD_NUMBER = 2;
    private double hum_ = 0D;
    /**
     * <code>double hum = 2;</code>
     * @return The hum.
     */
    @java.lang.Override
    public double getHum() {
      return hum_;
    }

    public static final int ONLINE_FIELD_NUMBER = 3;
    private boolean online_ = false;
    /**
     * <code>bool online = 3;</code>
     * @return The online.
     */
    @java.lang.Override
    public boolean getOnline() {
      return online_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(temp_) != 0) {
        output.writeDouble(1, temp_);
      }
      if (java.lang.Double.doubleToRawLongBits(hum_) != 0) {
        output.writeDouble(2, hum_);
      }
      if (online_ != false) {
        output.writeBool(3, online_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(temp_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, temp_);
      }
      if (java.lang.Double.doubleToRawLongBits(hum_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, hum_);
      }
      if (online_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, online_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.TelemetryProto.Reading)) {
        return super.equals(obj);
      }
      com.example.proto.TelemetryProto.Reading other = (com.example.proto.TelemetryProto.Reading) obj;

      if (java.lang.Double.doubleToLongBits(getTemp())
          != java.lang.Double.doubleToLongBits(
              other.getTemp())) return false;
      if (java.lang.Double.doubleToLongBits(getHum())
          != java.lang.Double.doubleToLongBits(
              other.getHum())) return false;
      if (getOnline()
          != other.getOnline()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTemp()));
      hash = (37 * hash) + HUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHum()));
      hash = (37 * hash) + ONLINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOnline());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.TelemetryProto.Reading parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.TelemetryProto.Reading parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Reading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.TelemetryProto.Reading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Reading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.TelemetryProto.Reading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Reading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.TelemetryProto.Reading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.proto.TelemetryProto.Reading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.proto.TelemetryProto.Reading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Reading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.TelemetryProto.Reading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.TelemetryProto.Reading prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.telemetry.Reading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.telemetry.Reading)
        com.example.proto.TelemetryProto.ReadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.TelemetryProto.internal_static_example_telemetry_Reading_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.TelemetryProto.internal_static_example_telemetry_Reading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.TelemetryProto.Reading.class, com.example.proto.TelemetryProto.Reading.Builder.class);
      }

      // Construct using com.example.proto.TelemetryProto.Reading.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        temp_ = 0D;
        hum_ = 0D;
        online_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.TelemetryProto.internal_static_example_telemetry_Reading_descriptor;
      }

      @java.lang.Override
      public com.example.proto.TelemetryProto.Reading getDefaultInstanceForType() {
        return com.example.proto.TelemetryProto.Reading.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.TelemetryProto.Reading build() {
        com.example.proto.TelemetryProto.Reading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.TelemetryProto.Reading buildPartial() {
        com.example.proto.TelemetryProto.Reading result = new com.example.proto.TelemetryProto.Reading(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.proto.TelemetryProto.Reading result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.temp_ = temp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.hum_ = hum_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.online_ = online_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.TelemetryProto.Reading) {
          return mergeFrom((com.example.proto.TelemetryProto.Reading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.TelemetryProto.Reading other) {
        if (other == com.example.proto.TelemetryProto.Reading.getDefaultInstance()) return this;
        if (other.getTemp() != 0D) {
          setTemp(other.getTemp());
        }
        if (other.getHum() != 0D) {
          setHum(other.getHum());
        }
        if (other.getOnline() != false) {
          setOnline(other.getOnline());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                temp_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                hum_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 24: {
                online_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double temp_ ;
      /**
       * <code>double temp = 1;</code>
       * @return The temp.
       */
      @java.lang.Override
      public double getTemp() {
        return temp_;
      }
      /**
       * <code>double temp = 1;</code>
       * @param value The temp to set.
       * @return This builder for chaining.
       */
      public Builder setTemp(double value) {

        temp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double temp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        temp_ = 0D;
        onChanged();
        return this;
      }

      private double hum_ ;
      /**
       * <code>double hum = 2;</code>
       * @return The hum.
       */
      @java.lang.Override
      public double getHum() {
        return hum_;
      }
      /**
       * <code>double hum = 2;</code>
       * @param value The hum to set.
       * @return This builder for chaining.
       */
      public Builder setHum(double value) {

        hum_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double hum = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hum_ = 0D;
        onChanged();
        return this;
      }

      private boolean online_ ;
      /**
       * <code>bool online = 3;</code>
       * @return The online.
       */
      @java.lang.Override
      public boolean getOnline() {
        return online_;
      }
      /**
       * <code>bool online = 3;</code>
       * @param value The online to set.
       * @return This builder for chaining.
       */
      public Builder setOnline(boolean value) {

        online_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool online = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOnline() {
        bitField0_ = (bitField0_ & ~0x00000004);
        online_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:example.telemetry.Reading)
    }

    // @@protoc_insertion_point(class_scope:example.telemetry.Reading)
    private static final com.example.proto.TelemetryProto.Reading DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.TelemetryProto.Reading();
    }

    public static com.example.proto.TelemetryProto.Reading getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Reading>
        PARSER = new com.google.protobuf.AbstractParser<Reading>() {
      @java.lang.Override
      public Reading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Reading> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reading> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.TelemetryProto.Reading getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SensorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.telemetry.Sensor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string device = 1;</code>
     * @return The device.
     */
    java.lang.String getDevice();
    /**
     * <code>string device = 1;</code>
     * @return The bytes for device.
     */
    com.google.protobuf.ByteString
        getDeviceBytes();

    /**
     * <code>.example.telemetry.Reading reading = 2;</code>
     * @return Whether the reading field is set.
     */
    boolean hasReading();
    /**
     * <code>.example.telemetry.Reading reading = 2;</code>
     * @return The reading.
     */
    com.example.proto.TelemetryProto.Reading getReading();
    /**
     * <code>.example.telemetry.Reading reading = 2;</code>
     */
    com.example.proto.TelemetryProto.ReadingOrBuilder getReadingOrBuilder();
  }
  /**
   * Protobuf type {@code example.telemetry.Sensor}
   */
  public static final class Sensor extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:example.telemetry.Sensor)
      SensorOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        Sensor.class.getName());
    }
    // Use Sensor.newBuilder() to construct.
    private Sensor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Sensor() {
      device_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.TelemetryProto.internal_static_example_telemetry_Sensor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.TelemetryProto.internal_static_example_telemetry_Sensor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.TelemetryProto.Sensor.class, com.example.proto.TelemetryProto.Sensor.Builder.class);
    }

    private int bitField0_;
    public static final int DEVICE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object device_ = "";
    /**
     * <code>string device = 1;</code>
     * @return The device.
     */
    @java.lang.Override
    public java.lang.String getDevice() {
      java.lang.Object ref = device_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        device_ = s;
        return s;
      }
    }
    /**
     * <code>string device = 1;</code>
     * @return The bytes for device.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceBytes() {
      java.lang.Object ref = device_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        device_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int READING_FIELD_NUMBER = 2;
    private com.example.proto.TelemetryProto.Reading reading_;
    /**
     * <code>.example.telemetry.Reading reading = 2;</code>
     * @return Whether the reading field is set.
     */
    @java.lang.Override
    public boolean hasReading() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.example.telemetry.Reading reading = 2;</code>
     * @return The reading.
     */
    @java.lang.Override
    public com.example.proto.TelemetryProto.Reading getReading() {
      return reading_ == null ? com.example.proto.TelemetryProto.Reading.getDefaultInstance() : reading_;
    }
    /**
     * <code>.example.telemetry.Reading reading = 2;</code>
     */
    @java.lang.Override
    public com.example.proto.TelemetryProto.ReadingOrBuilder getReadingOrBuilder() {
      return reading_ == null ? com.example.proto.TelemetryProto.Reading.getDefaultInstance() : reading_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(device_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, device_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getReading());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(device_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, device_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getReading());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.TelemetryProto.Sensor)) {
        return super.equals(obj);
      }
      com.example.proto.TelemetryProto.Sensor other = (com.example.proto.TelemetryProto.Sensor) obj;

      if (!getDevice()
          .equals(other.getDevice())) return false;
      if (hasReading() != other.hasReading()) return false;
      if (hasReading()) {
        if (!getReading()
            .equals(other.getReading())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_FIELD_NUMBER;
      hash = (53 * hash) + getDevice().hashCode();
      if (hasReading()) {
        hash = (37 * hash) + READING_FIELD_NUMBER;
        hash = (53 * hash) + getReading().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.TelemetryProto.Sensor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.TelemetryProto.Sensor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Sensor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.TelemetryProto.Sensor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Sensor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.TelemetryProto.Sensor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Sensor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.TelemetryProto.Sensor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.proto.TelemetryProto.Sensor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.proto.TelemetryProto.Sensor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Sensor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.TelemetryProto.Sensor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.TelemetryProto.Sensor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.telemetry.Sensor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.telemetry.Sensor)
        com.example.proto.TelemetryProto.SensorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.TelemetryProto.internal_static_example_telemetry_Sensor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.TelemetryProto.internal_static_example_telemetry_Sensor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.TelemetryProto.Sensor.class, com.example.proto.TelemetryProto.Sensor.Builder.class);
      }

      // Construct using com.example.proto.TelemetryProto.Sensor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getReadingFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        device_ = "";
        reading_ = null;
        if (readingBuilder_ != null) {
          readingBuilder_.dispose();
          readingBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.TelemetryProto.internal_static_example_telemetry_Sensor_descriptor;
      }

      @java.lang.Override
      public com.example.proto.TelemetryProto.Sensor getDefaultInstanceForType() {
        return com.example.proto.TelemetryProto.Sensor.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.TelemetryProto.Sensor build() {
        com.example.proto.TelemetryProto.Sensor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.TelemetryProto.Sensor buildPartial() {
        com.example.proto.TelemetryProto.Sensor result = new com.example.proto.TelemetryProto.Sensor(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.proto.TelemetryProto.Sensor result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.device_ = device_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.reading_ = readingBuilder_ == null
              ? reading_
              : readingBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.TelemetryProto.Sensor) {
          return mergeFrom((com.example.proto.TelemetryProto.Sensor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.TelemetryProto.Sensor other) {
        if (other == com.example.proto.TelemetryProto.Sensor.getDefaultInstance()) return this;
        if (!other.getDevice().isEmpty()) {
          device_ = other.device_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasReading()) {
          mergeReading(other.getReading());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                device_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getReadingFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object device_ = "";
      /**
       * <code>string device = 1;</code>
       * @return The device.
       */
      public java.lang.String getDevice() {
        java.lang.Object ref = device_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          device_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device = 1;</code>
       * @return The bytes for device.
       */
      public com.google.protobuf.ByteString
          getDeviceBytes() {
        java.lang.Object ref = device_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          device_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device = 1;</code>
       * @param value The device to set.
       * @return This builder for chaining.
       */
      public Builder setDevice(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        device_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string device = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDevice() {
        device_ = getDefaultInstance().getDevice();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string device = 1;</code>
       * @param value The bytes for device to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        device_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.example.proto.TelemetryProto.Reading reading_;
      private com.google.protobuf.SingleFieldBuilder<
          com.example.proto.TelemetryProto.Reading, com.example.proto.TelemetryProto.Reading.Builder, com.example.proto.TelemetryProto.ReadingOrBuilder> readingBuilder_;
      /**
       * <code>.example.telemetry.Reading reading = 2;</code>
       * @return Whether the reading field is set.
       */
      public boolean hasReading() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.example.telemetry.Reading reading = 2;</code>
       * @return The reading.
       */
      public com.example.proto.TelemetryProto.Reading getReading() {
        if (readingBuilder_ == null) {
          return reading_ == null ? com.example.proto.TelemetryProto.Reading.getDefaultInstance() : reading_;
        } else {
          return readingBuilder_.getMessage();
        }
      }
      /**
       * <code>.example.telemetry.Reading reading = 2;</code>
       */
      public Builder setReading(com.example.proto.TelemetryProto.Reading value) {
        if (readingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reading_ = value;
        } else {
          readingBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.example.telemetry.Reading reading = 2;</code>
       */
      public Builder setReading(
          com.example.proto.TelemetryProto.Reading.Builder builderForValue) {
        if (readingBuilder_ == null) {
          reading_ = builderForValue.build();
        } else {
          readingBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.example.telemetry.Reading reading = 2;</code>
       */
      public Builder mergeReading(com.example.proto.TelemetryProto.Reading value) {
        if (readingBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            reading_ != null &&
            reading_ != com.example.proto.TelemetryProto.Reading.getDefaultInstance()) {
            getReadingBuilder().mergeFrom(value);
          } else {
            reading_ = value;
          }
        } else {
          readingBuilder_.mergeFrom(value);
        }
        if (reading_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.example.telemetry.Reading reading = 2;</code>
       */
      public Builder clearReading() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reading_ = null;
        if (readingBuilder_ != null) {
          readingBuilder_.dispose();
          readingBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.example.telemetry.Reading reading = 2;</code>
       */
      public com.example.proto.TelemetryProto.Reading.Builder getReadingBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getReadingFieldBuilder().getBuilder();
      }
      /**
       * <code>.example.telemetry.Reading reading = 2;</code>
       */
      public com.example.proto.TelemetryProto.ReadingOrBuilder getReadingOrBuilder() {
        if (readingBuilder_ != null) {
          return readingBuilder_.getMessageOrBuilder();
        } else {
          return reading_ == null ?
              com.example.proto.TelemetryProto.Reading.getDefaultInstance() : reading_;
        }
      }
      /**
       * <code>.example.telemetry.Reading reading = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.proto.TelemetryProto.Reading, com.example.proto.TelemetryProto.Reading.Builder, com.example.proto.TelemetryProto.ReadingOrBuilder> 
          getReadingFieldBuilder() {
        if (readingBuilder_ == null) {
          readingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.proto.TelemetryProto.Reading, com.example.proto.TelemetryProto.Reading.Builder, com.example.proto.TelemetryProto.ReadingOrBuilder>(
                  getReading(),
                  getParentForChildren(),
                  isClean());
          reading_ = null;
        }
        return readingBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:example.telemetry.Sensor)
    }

    // @@protoc_insertion_point(class_scope:example.telemetry.Sensor)
    private static final com.example.proto.TelemetryProto.Sensor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.TelemetryProto.Sensor();
    }

    public static com.example.proto.TelemetryProto.Sensor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sensor>
        PARSER = new com.google.protobuf.AbstractParser<Sensor>() {
      @java.lang.Override
      public Sensor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Sensor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sensor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.TelemetryProto.Sensor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.telemetry.Envelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.example.telemetry.Sensor sensor = 1;</code>
     * @return Whether the sensor field is set.
     */
    boolean hasSensor();
    /**
     * <code>.example.telemetry.Sensor sensor = 1;</code>
     * @return The sensor.
     */
    com.example.proto.TelemetryProto.Sensor getSensor();
    /**
     * <code>.example.telemetry.Sensor sensor = 1;</code>
     */
    com.example.proto.TelemetryProto.SensorOrBuilder getSensorOrBuilder();

    /**
     * <code>string site = 2;</code>
     * @return The site.
     */
    java.lang.String getSite();
    /**
     * <code>string site = 2;</code>
     * @return The bytes for site.
     */
    com.google.protobuf.ByteString
        getSiteBytes();
  }
  /**
   * Protobuf type {@code example.telemetry.Envelope}
   */
  public static final class Envelope extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:example.telemetry.Envelope)
      EnvelopeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        Envelope.class.getName());
    }
    // Use Envelope.newBuilder() to construct.
    private Envelope(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Envelope() {
      site_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.TelemetryProto.internal_static_example_telemetry_Envelope_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.TelemetryProto.internal_static_example_telemetry_Envelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.TelemetryProto.Envelope.class, com.example.proto.TelemetryProto.Envelope.Builder.class);
    }

    private int bitField0_;
    public static final int SENSOR_FIELD_NUMBER = 1;
    private com.example.proto.TelemetryProto.Sensor sensor_;
    /**
     * <code>.example.telemetry.Sensor sensor = 1;</code>
     * @return Whether the sensor field is set.
     */
    @java.lang.Override
    public boolean hasSensor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.example.telemetry.Sensor sensor = 1;</code>
     * @return The sensor.
     */
    @java.lang.Override
    public com.example.proto.TelemetryProto.Sensor getSensor() {
      return sensor_ == null ? com.example.proto.TelemetryProto.Sensor.getDefaultInstance() : sensor_;
    }
    /**
     * <code>.example.telemetry.Sensor sensor = 1;</code>
     */
    @java.lang.Override
    public com.example.proto.TelemetryProto.SensorOrBuilder getSensorOrBuilder() {
      return sensor_ == null ? com.example.proto.TelemetryProto.Sensor.getDefaultInstance() : sensor_;
    }

    public static final int SITE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object site_ = "";
    /**
     * <code>string site = 2;</code>
     * @return The site.
     */
    @java.lang.Override
    public java.lang.String getSite() {
      java.lang.Object ref = site_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        site_ = s;
        return s;
      }
    }
    /**
     * <code>string site = 2;</code>
     * @return The bytes for site.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSiteBytes() {
      java.lang.Object ref = site_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        site_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getSensor());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(site_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, site_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSensor());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(site_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, site_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.TelemetryProto.Envelope)) {
        return super.equals(obj);
      }
      com.example.proto.TelemetryProto.Envelope other = (com.example.proto.TelemetryProto.Envelope) obj;

      if (hasSensor() != other.hasSensor()) return false;
      if (hasSensor()) {
        if (!getSensor()
            .equals(other.getSensor())) return false;
      }
      if (!getSite()
          .equals(other.getSite())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSensor()) {
        hash = (37 * hash) + SENSOR_FIELD_NUMBER;
        hash = (53 * hash) + getSensor().hashCode();
      }
      hash = (37 * hash) + SITE_FIELD_NUMBER;
      hash = (53 * hash) + getSite().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.TelemetryProto.Envelope parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.TelemetryProto.Envelope parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Envelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.TelemetryProto.Envelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Envelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.TelemetryProto.Envelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Envelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.TelemetryProto.Envelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.proto.TelemetryProto.Envelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.proto.TelemetryProto.Envelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.TelemetryProto.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.TelemetryProto.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.TelemetryProto.Envelope prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.telemetry.Envelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.telemetry.Envelope)
        com.example.proto.TelemetryProto.EnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.TelemetryProto.internal_static_example_telemetry_Envelope_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.TelemetryProto.internal_static_example_telemetry_Envelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.TelemetryProto.Envelope.class, com.example.proto.TelemetryProto.Envelope.Builder.class);
      }

      // Construct using com.example.proto.TelemetryProto.Envelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getSensorFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sensor_ = null;
        if (sensorBuilder_ != null) {
          sensorBuilder_.dispose();
          sensorBuilder_ = null;
        }
        site_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.TelemetryProto.internal_static_example_telemetry_Envelope_descriptor;
      }

      @java.lang.Override
      public com.example.proto.TelemetryProto.Envelope getDefaultInstanceForType() {
        return com.example.proto.TelemetryProto.Envelope.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.TelemetryProto.Envelope build() {
        com.example.proto.TelemetryProto.Envelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.TelemetryProto.Envelope buildPartial() {
        com.example.proto.TelemetryProto.Envelope result = new com.example.proto.TelemetryProto.Envelope(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.proto.TelemetryProto.Envelope result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sensor_ = sensorBuilder_ == null
              ? sensor_
              : sensorBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.site_ = site_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.TelemetryProto.Envelope) {
          return mergeFrom((com.example.proto.TelemetryProto.Envelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.TelemetryProto.Envelope other) {
        if (other == com.example.proto.TelemetryProto.Envelope.getDefaultInstance()) return this;
        if (other.hasSensor()) {
          mergeSensor(other.getSensor());
        }
        if (!other.getSite().isEmpty()) {
          site_ = other.site_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getSensorFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                site_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.example.proto.TelemetryProto.Sensor sensor_;
      private com.google.protobuf.SingleFieldBuilder<
          com.example.proto.TelemetryProto.Sensor, com.example.proto.TelemetryProto.Sensor.Builder, com.example.proto.TelemetryProto.SensorOrBuilder> sensorBuilder_;
      /**
       * <code>.example.telemetry.Sensor sensor = 1;</code>
       * @return Whether the sensor field is set.
       */
      public boolean hasSensor() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.example.telemetry.Sensor sensor = 1;</code>
       * @return The sensor.
       */
      public com.example.proto.TelemetryProto.Sensor getSensor() {
        if (sensorBuilder_ == null) {
          return sensor_ == null ? com.example.proto.TelemetryProto.Sensor.getDefaultInstance() : sensor_;
        } else {
          return sensorBuilder_.getMessage();
        }
      }
      /**
       * <code>.example.telemetry.Sensor sensor = 1;</code>
       */
      public Builder setSensor(com.example.proto.TelemetryProto.Sensor value) {
        if (sensorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sensor_ = value;
        } else {
          sensorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.example.telemetry.Sensor sensor = 1;</code>
       */
      public Builder setSensor(
          com.example.proto.TelemetryProto.Sensor.Builder builderForValue) {
        if (sensorBuilder_ == null) {
          sensor_ = builderForValue.build();
        } else {
          sensorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.example.telemetry.Sensor sensor = 1;</code>
       */
      public Builder mergeSensor(com.example.proto.TelemetryProto.Sensor value) {
        if (sensorBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            sensor_ != null &&
            sensor_ != com.example.proto.TelemetryProto.Sensor.getDefaultInstance()) {
            getSensorBuilder().mergeFrom(value);
          } else {
            sensor_ = value;
          }
        } else {
          sensorBuilder_.mergeFrom(value);
        }
        if (sensor_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.example.telemetry.Sensor sensor = 1;</code>
       */
      public Builder clearSensor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sensor_ = null;
        if (sensorBuilder_ != null) {
          sensorBuilder_.dispose();
          sensorBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.example.telemetry.Sensor sensor = 1;</code>
       */
      public com.example.proto.TelemetryProto.Sensor.Builder getSensorBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSensorFieldBuilder().getBuilder();
      }
      /**
       * <code>.example.telemetry.Sensor sensor = 1;</code>
       */
      public com.example.proto.TelemetryProto.SensorOrBuilder getSensorOrBuilder() {
        if (sensorBuilder_ != null) {
          return sensorBuilder_.getMessageOrBuilder();
        } else {
          return sensor_ == null ?
              com.example.proto.TelemetryProto.Sensor.getDefaultInstance() : sensor_;
        }
      }
      /**
       * <code>.example.telemetry.Sensor sensor = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.proto.TelemetryProto.Sensor, com.example.proto.TelemetryProto.Sensor.Builder, com.example.proto.TelemetryProto.SensorOrBuilder> 
          getSensorFieldBuilder() {
        if (sensorBuilder_ == null) {
          sensorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.proto.TelemetryProto.Sensor, com.example.proto.TelemetryProto.Sensor.Builder, com.example.proto.TelemetryProto.SensorOrBuilder>(
                  getSensor(),
                  getParentForChildren(),
                  isClean());
          sensor_ = null;
        }
        return sensorBuilder_;
      }

      private java.lang.Object site_ = "";
      /**
       * <code>string site = 2;</code>
       * @return The site.
       */
      public java.lang.String getSite() {
        java.lang.Object ref = site_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          site_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string site = 2;</code>
       * @return The bytes for site.
       */
      public com.google.protobuf.ByteString
          getSiteBytes() {
        java.lang.Object ref = site_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          site_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string site = 2;</code>
       * @param value The site to set.
       * @return This builder for chaining.
       */
      public Builder setSite(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        site_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string site = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSite() {
        site_ = getDefaultInstance().getSite();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string site = 2;</code>
       * @param value The bytes for site to set.
       * @return This builder for chaining.
       */
      public Builder setSiteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        site_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:example.telemetry.Envelope)
    }

    // @@protoc_insertion_point(class_scope:example.telemetry.Envelope)
    private static final com.example.proto.TelemetryProto.Envelope DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.TelemetryProto.Envelope();
    }

    public static com.example.proto.TelemetryProto.Envelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Envelope>
        PARSER = new com.google.protobuf.AbstractParser<Envelope>() {
      @java.lang.Override
      public Envelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Envelope> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Envelope> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.TelemetryProto.Envelope getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_telemetry_Reading_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_telemetry_Reading_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_telemetry_Sensor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_telemetry_Sensor_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_telemetry_Envelope_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_telemetry_Envelope_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017telemetry.proto\022\021example.telemetry\"4\n\007" +
      "Reading\022\014\n\004temp\030\001 \001(\001\022\013\n\003hum\030\002 \001(\001\022\016\n\006on" +
      "line\030\003 \001(\010\"E\n\006Sensor\022\016\n\006device\030\001 \001(\t\022+\n\007" +
      "reading\030\002 \001(\0132\032.example.telemetry.Readin" +
      "g\"C\n\010Envelope\022)\n\006sensor\030\001 \001(\0132\031.example." +
      "telemetry.Sensor\022\014\n\004site\030\002 \001(\tB#\n\021com.ex" +
      "ample.protoB\016TelemetryProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_telemetry_Reading_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_telemetry_Reading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_telemetry_Reading_descriptor,
        new java.lang.String[] { "Temp", "Hum", "Online", });
    internal_static_example_telemetry_Sensor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_telemetry_Sensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_telemetry_Sensor_descriptor,
        new java.lang.String[] { "Device", "Reading", });
    internal_static_example_telemetry_Envelope_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_example_telemetry_Envelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_telemetry_Envelope_descriptor,
        new java.lang.String[] { "Sensor", "Site", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
